#  This workflow builds a new docker image for a regression tests The image
#  will be built from the input variables and pushed to ghcr.io if the path to
#  this image's version file has changed

name: Build and publish an image

on:
  workflow_call:
    inputs:
      image-short-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout regression test repository
        uses: actions/checkout@v3

      - name: Build Image
        working-directory: ./test
        run: |
          make ${{inputs.image-short-name}}-image
