# This workflow runs variable-subsetter regression test suite, using the tag from the workflow call.
#
# Required settings in the repository:
# Environments (exactly the following strings):
# - prod
# - uat
# - sit
#
# Secrets in each environment:
# - EDL_USER
# - EDL_PASSWORD
#
# Note: A workflow_call event can only have inputs of type boolean, number or
# string.
name: Run variable-subsetter test suite

on:
  workflow_call:
    inputs:
      harmony-environment:
        required: true
        type: string
      docker-image-tag:
        required: false
        type: string
        default: 'latest'

  repository_dispatch:
    types: [harmony-service-example]
    inputs:
      harmony-environment:
        required: true
        type: choice
        options:
          - sit
          - uat
          - prod
      docker-image-tag:
        required: false
        type: string
        default: 'latest'

jobs:
  base_job:
    environment: ${{ github.event.client_payload.harmony-environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the URL of the current workflow run
        run: echo "RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Set HARMONY_HOST_URL
        run: |
          if [ "${{ github.event.client_payload.harmony-environment }}" == "uat" ]; then
            echo "HARMONY_HOST_URL=https://harmony.uat.earthdata.nasa.gov"
            echo "HARMONY_HOST_URL=https://harmony.uat.earthdata.nasa.gov" >> $GITHUB_ENV
          elif [ "${{ github.event.client_payload.harmony-environment }}" == "prod" ]; then
            echo "HARMONY_HOST_URL=https://harmony.earthdata.nasa.gov"
            echo "HARMONY_HOST_URL=https://harmony.earthdata.nasa.gov" >> $GITHUB_ENV
          else
            echo "HARMONY_HOST_URL=https://harmony.sit.earthdata.nasa.gov"
            echo "HARMONY_HOST_URL=https://harmony.sit.earthdata.nasa.gov" >> $GITHUB_ENV
          fi

      - name: Load Harmony Service Config from Environment Variable
        id: load-config
        run: |
          # Use the event type to select the appropriate service list
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "SERVICES_TESTS=$(echo '${{ vars.SERVICES_TESTS_CONFIG }}' | jq -r '."${{ github.event.action || github.event_name }}"')" >> $GITHUB_ENV

      - name: Create Matrix Configuration
        id: create-matrix
        run: |
          # Split the selected service list into an array format and set it as the matrix
          echo "::set-output name=matrix::$(echo "${{ env.SERVICES_TESTS }}" | tr ',' '\n' | jq -c -R '[inputs] | {service: .}')"

  run-tests:
    needs: base_job
    environment: ${{ github.event.client_payload.harmony-environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.base_job.outputs['create-matrix.matrix']) }}

    steps:
      - name: Pull Docker image
        run: docker pull ghcr.io/nasa/regression-tests-${{ matrix.service }}:${{ github.event.client_payload.docker-image-tag || 'latest' }}

      - name: Execute notebook
        id: test-step
        working-directory: ./test
        env:
          EDL_USER: ${{ secrets.EDL_USER }}
          EDL_PASSWORD: ${{ secrets.EDL_PASSWORD }}
          HARMONY_HOST_URL: ${{ env.HARMONY_HOST_URL }}
        run: ./run_notebooks.sh ${{ matrix.service }}

      - name: Save notebook as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: notebook-output
          path: test/output/${{ matrix.service }}/Results.ipynb

      - name: Set Test Outcome
        if: always()
        run: echo "::set-output name=outcome::${{ steps.test-step.outcome }}"

  email_job:
    needs: run-tests
    environment: ${{ github.event.client_payload.harmony-environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: variable-subsetter regression test result is ${{ needs.run-tests.outputs.outcome }}
          to: ${{ vars.TO_EMAIL_VARIABLE_SUBSETTER }}
          from: ${{ secrets.FROM_EMAIL }}
          body: ${{ matrix.service }} regression test result is ${{ needs.run-tests.outputs.outcome }}! View the details at ${{ env.RUN_URL }}.
